config/routes.rb
Rails.application.routes.draw do

  root to: redirect('/hendrix')

  get   '/admin',         to: "admins#index"
  get   '/:slug/admin',   to: "admins#show",    as: "location_admin"

  get   '/login',         to: "sessions#new"
  post  '/login',         to: "sessions#create"
  get   '/logout',        to: "sessions#destroy"

  resources :locations, param: :slug, path: "", :only => [:show] do

    resources :posts, :only => [:index, :create, :destroy] do

      post '/flag',       to: 'posts#flag'
      post '/clear',      to: 'posts#clear'

      resources :comments, :only => [:create, :destroy] do

        post '/flag',     to: 'comments#flag'
        post '/clear',    to: 'comments#clear'

      end

    end
  end

end

app/views/admins/_show_headers.html.erb
  <tr>
    <th class="admin-time">Timestamp</th>
    <th class="admin-location">Location</th>
    <th class="admin-hair">Hair</th>
    <th class="admin-gender">Gender</th>
    <th class="admin-content">Content</th>
    <th class="admin-flags">Flags</th>
    <th class="admin-show">Show</th>
    <th class="admin-ok"></th>
    <th class="admin-hide"></th>
  </tr>

app/views/admins/_show_row_comment.html.erb
<% if comment.clear? %>
  <tr class="admin-comment">
<% else %>
    <tr class="admin-comment-hidden">
<% end %>
  <td class="admin-time"><%= comment.created_at.strftime("%m/%d %H:%M") %></td>
  <td colspan="3" class="admin-comment-blank"></td>
  <td class="admin-content"><%= "#{comment.author_name}: #{comment.content}" %></td>
  <td class="admin-flags"><%= comment.flagged %></td>
  <% if comment.clear? %>
    <td class="admin-show">Y</td>
  <% else %>
    <td class="admin-show-no">N</td>
  <% end %>
  <td class="admin-ok"><%= button_to "OK", location_post_comment_clear_path(location, post, comment), method: "POST" %></td>
  <td class="admin-remove"><%= button_to "Hide", location_post_comment_path(location, post, comment), method: :delete, data: {confirm: "Are you sure?"} %></td>
</tr>

app/views/admins/_show_row_post.html.erb
<% if post.clear? %>
  <tbody class="admin-post-grouping admin-post-grouping-showing">
<% else %>
  <tbody class="admin-post-grouping admin-post-grouping-hidden">
<% end %>

  <tr class="admin-post">
    <td class="admin-time"><%= post.created_at.strftime("%m/%d %H:%M") %></td>
    <td class="admin-location"><%= post.spotted_at %></td>
    <td class="admin-hair"><%= post.hair %></td>
    <td class="admin-gender"><%= post.gender %></td>
    <td class="admin-content"><%= post.content %></td>
    <td class="admin-flags"><%= post.flagged %></td>
    <% if post.clear? %>
      <td class="admin-show admin-show-yes">Y</td>
    <% else %>
      <td class="admin-show admin-show-no">N</td>
    <% end %>
    <td class="admin-ok"><%= button_to "OK", location_post_clear_path(location, post), method: "POST" if post.status <= 0%></td>
    <td class="admin-hide"><%= button_to "Hide", location_post_path(location, post), method: :delete, data: {confirm: "Are you sure?"} if post.status >= -1 %></td>
  </tr>

  <% post.comments.each do |comment| %>
    <%= render partial: "show_row_comment", locals: {location: location, post: post, comment: comment} %>
  <% end %>
</tbody>

app/views/admins/index.html.erb
<!-- To be fleshed out -->

<ul>
<% @locations.each do |location| %>
  <li><%= link_to location.name, location_admin_path(location) %></li>
<% end %>
<ul>

<%= link_to "Logout", logout_path %>

app/views/admins/show.html.erb
<%= link_to "Back to locations", admin_path %>
<%= link_to "Logout", logout_path %>

<div id="admin-tables">
  <table class="admin-table">
    <tr><td colspan="9">PRIORITIES (flagged by users)</tr>
    <%= render "show_headers" %>

    <% @admin.priorities.each do |post| %>
      <%= render partial: "show_row_post", locals: {location: @admin.location, post: post} %>
    <% end %>
  </table>

  <table class="admin-table">
    <tr><td colspan="9">ALL POSTS</td></tr>
    <%= render "show_headers" %>

    <% @admin.posts.each do |post| %>
      <%= render partial: "show_row_post", locals: {location: @admin.location, post: post} %>
    <% end %>

  </table>
</div>