config/routes.rb
Rails.application.routes.draw do

  root to: redirect('/hendrix')

  get   '/admin',         to: "admins#index"
  get   '/:slug/admin',   to: "admins#show",    as: "location_admin"

  get   '/login',         to: "sessions#new"
  post  '/login',         to: "sessions#create"
  get   '/logout',        to: "sessions#destroy"

  resources :locations, param: :slug, path: "", :only => [:show] do

    resources :posts, :only => [:index, :create, :destroy] do

      post '/flag',       to: 'posts#flag'
      post '/clear',      to: 'posts#clear'

      resources :comments, :only => [:create, :destroy] do

        post '/flag',     to: 'comments#flag'
        post '/clear',    to: 'comments#clear'

      end

    end
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :posts
  has_many :administrations
  has_many :admins, through: :administrations

  validates :name, presence: true

  after_create :generate_slug

  def to_param
    slug
  end

    private

  def generate_slug
    self.slug ||= name.downcase.strip.gsub(/ /, '-')
    save
  end

end

app/controllers/location_controller.rb
class LocationController < ApplicationController

  def show
    url = params[:location_name].downcase.strip
    @location = Location.find_by(slug: url)
    redirect_to '/' unless @location
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :get_location

  def show
  end

    private

  def get_location
    url = params[:slug].downcase.strip
    @location = Location.find_by(slug: url)
    redirect_to '/' unless @location
  end

end

app/views/locations/_admin_headers.html.erb
  <tr>
    <th class="admin-time">Timestamp</th>
    <th class="admin-location">Location</th>
    <th class="admin-hair">Hair</th>
    <th class="admin-gender">Gender</th>
    <th class="admin-content">Content</th>
    <th class="admin-flags">Flags</th>
    <th class="admin-show">Show</th>
    <th class="admin-ok"></th>
    <th class="admin-hide"></th>
  </tr>

app/views/locations/_admin_row_comment.html.erb
<% if comment.clear? %>
  <tr class="admin-comment">
<% else %>
    <tr class="admin-comment-hidden">
<% end %>
  <td class="admin-time"><%= comment.created_at.strftime("%m/%d %H:%M") %></td>
  <td colspan="3" class="admin-comment-blank"></td>
  <td class="admin-content"><%= "#{comment.author_name}: #{comment.content}" %></td>
  <td class="admin-flags"><%= comment.flagged %></td>
  <% if comment.clear? %>
    <td class="admin-show">Y</td>
  <% else %>
    <td class="admin-show-no">N</td>
  <% end %>
  <td class="admin-ok"><%= button_to "OK", location_post_comment_clear_path(location, post, comment), method: "POST" %></td>
  <td class="admin-remove"><%= button_to "Hide", location_post_comment_path(location, post, comment), method: :delete, data: {confirm: "Are you sure?"} %></td>
</tr>

app/views/locations/_admin_row_post.html.erb
<% if post.clear? %>
  <tbody class="admin-post-grouping admin-post-grouping-showing">
<% else %>
  <tbody class="admin-post-grouping admin-post-grouping-hidden">
<% end %>

  <tr class="admin-post">
    <td class="admin-time"><%= post.created_at.strftime("%m/%d %H:%M") %></td>
    <td class="admin-location"><%= post.spotted_at %></td>
    <td class="admin-hair"><%= post.hair %></td>
    <td class="admin-gender"><%= post.gender %></td>
    <td class="admin-content"><%= post.content %></td>
    <td class="admin-flags"><%= post.flagged %></td>
    <% if post.clear? %>
      <td class="admin-show admin-show-yes">Y</td>
    <% else %>
      <td class="admin-show admin-show-no">N</td>
    <% end %>
    <td class="admin-ok"><%= button_to "OK", location_post_clear_path(location, post), method: "POST" if post.status <= 0%></td>
    <td class="admin-hide"><%= button_to "Hide", location_post_path(location, post), method: :delete, data: {confirm: "Are you sure?"} if post.status >= -1 %></td>
  </tr>

  <% post.comments.each do |comment| %>
    <%= render partial: "admin_row_comment", locals: {location: location, post: post, comment: comment} %>
  <% end %>
</tbody>

app/views/locations/_demo_flash.html.erb
<div id="demo-flash-container" class="closable-container">
  <a href="#" id="demo-flash-close" class="close-icon"><%= icon('times-circle', '', {class: "fa-lg", id: 'demo-close-icon'}) %></a>

  <div id="demo-flash">
    Please feel free to try out posting, commenting, or reporting here.</br></br>

    The content for this page is deleted and regenerated hourly.</br></br>

    There is a live location that is (sometimes) posted to by users at <a href="http://www.posy.us/hendrix">posy.us/hendrix</a>.
  </div>
</div>

app/views/locations/_post_form.html.erb
<%= form_tag  location_posts_path(location.slug), 
              method: 'post', 
              id: 'new-post-form'  do %>
     
  <div id="new-form-gender" class="new-form-select">          
    <%= label_tag(:gender, "Gender") %>
    <%= select_tag(:gender, options_for_select(
      [
        ['', ''],
        ['Female', 'Female'],
        ['Male', 'Male'],
        ['Other', 'Other']
      ]), id: 'new-post-gender') 
    %>
  </div>

  <div id="new-form-hair" class="new-form-select">  
    <%= label_tag(:hair, "Hair") %>
    <%= select_tag(:hair, options_for_select(
      [
        ['', ''],
        ['Brown', 'brown'],
        ['Black', 'Black'],
        ['Blonde', 'Blonde'],
        ['Red', 'Red'],
        ['Other', 'Other']
      ]), id: 'new-post-hair') 
    %>
  </div>

  <div id="new-form-location">
    <%= label_tag(:location) do %>
      Location <span id="new-post-location-requirement">(required)</span>
    <% end %>
    <%= text_field_tag(:location, '', id: "new-post-location") %>
  </div>

  <div id="new-form-message">
    <%= label_tag(:message) do %>
      Message <span id="new-post-message-requirement">(required)</span>
    <% end %>
    <%= text_area_tag(:message, '', size: "24x6", id: 'new-post-message') %>
  </div>

  <%= submit_tag("Submit", id: "new-form-submit") %>
<% end %>

app/views/locations/show.html.erb
<div id="location-backdrop"></div>
<div id="location-container">
  <div id="location-header">
    <h1 id="location-brand">Posy</h1>

    <a href="#">
      <%= icon('pencil-square-o', '', {class: "fa-lg", id: "location-write-icon"}) %>
    </a>


  </div>


  <div id="location-body-container">
    <div id="location-body">


      <div id="location-details">
        <h2 id="location-name"><%= @location.name %></h2>
        <h3 id="location-description"><%= @location.description %></h3> 

        <%= render partial: 'demo_flash', locals: {location: @location} if @location.slug == 'demo' %>
      </div>

    <div id="location-new-post">
      <%= render partial: 'post_form', locals: {location: @location} %>
    </div>
      <div id="location-posts">
      </div> <!-- #location-posts -->

      <div id="location-complete">
      <%= icon('bolt', '', {class: "fa-lg", id:"location-complete-icon"}) %>
      </div>
    </div>

<!--     <a href="#">
      <%= icon('arrow-circle-up', '', {class: 'fa-lg', id: 'location-arrow-up'}) %>
    </a> -->
  </div> <!-- #location-body -->
</div>  <!-- #location-container -->